Added importing functionality in collaborative editing section.
syncfusion-content/ej2-spreadsheet-docs pull request #21
Opened 2023-07-17 08:27 UTC by Vasanth-3519

**Description:**
Added the importing functionality on collaborative editing mode in react UG documentation.

2023-07-17 08:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [collab-import-docs](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/15/)<br/>**

2023-07-24 07:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [collab-import-docs](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/18/)<br/>**

2023-07-24 08:34 UTC, gobalakrishnans requested changes

2023-07-24 08:34 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/use-cases/collaborative-editing.md
> +let spreadsheet: Spreadsheet = new Spreadsheet({
If you add directly to the MD file, Both JavaScript and TypeScript platform UG will display the Typescript code in all places. Need to add separate the code for JavaScript also.

https://ej2.syncfusion.com/javascript/documentation/spreadsheet/use-cases/collaborative-editing

https://ej2.syncfusion.com/documentation/spreadsheet/use-cases/collaborative-editing

2023-07-24 08:34 UTC, gobalakrishnans commented on ej2-javascript/code-snippet/spreadsheet/data-binding-cs2/index.js
> +        url:  'https://services.odata.org/V4/Northwind/Northwind.svc',
it will work if you removed the Orders from the URL ??

2023-07-31 05:46 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/data-binding-cs2/index.js
> +        url:  'https://services.odata.org/V4/Northwind/Northwind.svc',
Checked with the documentation and resolved.

2023-07-31 06:37 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/use-cases/collaborative-editing.md
> +    actionComplete: (args: any) => {
Checked and resolved

2023-07-31 07:30 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/use-cases/collaborative-editing.md
> +Using the `action` argument from the `actionComplete` event, you can identity whether the import action is performed or not. If the action is `import`, then you need to send the `response data` to th
Checked and added the referencce

2023-07-31 10:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [collab-import-docs](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/25/)<br/>**

2023-07-31 10:33 UTC, babu-periyasamy commented on ej2-javascript/spreadsheet/use-cases/collaborative-editing.md
> +let spreadsheet: Spreadsheet = new Spreadsheet({
Checked and added sample code for javascript.

2023-07-31 11:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [collab-import-docs](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/26/)<br/>**

2023-07-31 11:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [collab-import-docs](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/27/)<br/>**

2023-08-03 11:56 UTC, harivenkateshe commented on ej2-javascript/spreadsheet/js/use-cases/collaborative-editing.md
> +    .then(() => { // to start the server.
Standardize this comment.

2023-08-03 15:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [collab-import-docs](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/35/)<br/>**

2023-08-04 13:11 UTC, merged