Added column header change content under rows and columns.
syncfusion-content/ej2-spreadsheet-docs pull request #23
Opened 2023-07-20 13:55 UTC by Vasanth-3519

**Description:**
Added how to change the header text in column under rows and columns with sample code.

2023-07-20 13:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [column-header-change](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/17/)<br/>**

2023-07-24 08:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [column-header-change](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/19/)<br/>**

2023-07-31 10:21 UTC, gobalakrishnans requested changes

2023-07-31 10:21 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/rows-and-columns.md
> +## Modify the column header's text
Use "Change the text in the column headers"

2023-07-31 10:21 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/rows-and-columns.md
> +You can change the column header's text using the `beforeCellRender` event. And check whether the rendered cell is `headerCell` using `e-header-cell` class and modify its `innerHTML` based on the use
Use the below content and also map the API link to the event.

Using the `beforeCellRender` event, you can change the text in the column headers. In that event, you can use the `e-header-cell` class to identify the header cell element and update its text value.

2023-07-31 10:21 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/rows-and-columns.md
> +The following code example shows how to modify the column header's text in the spreadsheet.
Use the below content

The following code example shows how to change the text in the column headers.

2023-07-31 10:21 UTC, gobalakrishnans commented on ej2-javascript/code-snippet/spreadsheet/column-header-change-cs1/system.config.js
> +        "syncfusion:": "https://cdn.syncfusion.com/ej2/20.3.56/"
Use latest CDN link

2023-07-31 10:21 UTC, gobalakrishnans commented on ej2-javascript/code-snippet/spreadsheet/column-header-change-cs1/ts/index.html
> +        <link href="https://cdn.syncfusion.com/ej2/20.3.56/ej2-splitbuttons/styles/material.css" rel="stylesheet" />
Use latest CDN link to all CSS

2023-07-31 10:21 UTC, gobalakrishnans commented on ej2-javascript/code-snippet/spreadsheet/column-header-change-cs1/index.ts
> +        args.element.innerHTML = text;
Don't use the innerHTML , use innerText property or text

2023-07-31 11:29 UTC, babu-periyasamy commented on ej2-javascript/spreadsheet/rows-and-columns.md
> +## Modify the column header's text
Changed the content.

2023-07-31 11:29 UTC, babu-periyasamy commented on ej2-javascript/spreadsheet/rows-and-columns.md
> +You can change the column header's text using the `beforeCellRender` event. And check whether the rendered cell is `headerCell` using `e-header-cell` class and modify its `innerHTML` based on the use
Changed the content.

2023-07-31 11:29 UTC, babu-periyasamy commented on ej2-javascript/spreadsheet/rows-and-columns.md
> +The following code example shows how to modify the column header's text in the spreadsheet.
Changed the content.

2023-07-31 11:34 UTC, babu-periyasamy commented on ej2-javascript/code-snippet/spreadsheet/column-header-change-cs1/index.ts
> +        args.element.innerHTML = text;
Checked and changed to innerText.

2023-07-31 11:34 UTC, babu-periyasamy commented on ej2-javascript/code-snippet/spreadsheet/column-header-change-cs1/system.config.js
> +        "syncfusion:": "https://cdn.syncfusion.com/ej2/20.3.56/"
Added the latest CDN link.

2023-07-31 11:35 UTC, babu-periyasamy commented on ej2-javascript/code-snippet/spreadsheet/column-header-change-cs1/ts/index.html
> +        <link href="https://cdn.syncfusion.com/ej2/20.3.56/ej2-splitbuttons/styles/material.css" rel="stylesheet" />
Added the latest CDN links.

2023-07-31 11:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [column-header-change](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/28/console)**

2023-07-31 11:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [column-header-change](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/28/)<br/>**

2023-08-03 11:52 UTC, harivenkateshe commented on ej2-javascript/spreadsheet/rows-and-columns.md
> +## Change the text in the column headers
Change title like - "Changing text in column headers" for the below topic.

2023-08-03 16:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [column-header-change](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/36/console)**

2023-08-04 12:52 UTC, gobalakrishnans approved these changes

2023-08-04 12:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [column-header-change](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/37/console)**

2023-08-04 12:54 UTC, merged

2023-08-04 12:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [column-header-change](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/37/)<br/>**