Documentation(822850): To include the [FromForm] attribute in open/save documentation
syncfusion-content/ej2-spreadsheet-docs pull request #37
Opened 2023-08-16 13:36 UTC by sangeetha-priya-M

Feature description
Need to include the [FromForm] attribute in open/save documentation

Analysis and design
Included the  [FromForm] attribute in open/save documentation
Solution description
Included the  [FromForm] attribute in open/save documentation

Output Screenshot
NA

Areas affected and ensured
NA

Test cases
NA

2023-08-16 13:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/48/console)**

2023-08-16 13:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/48/)<br/>**

2023-09-20 07:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/56/)<br/>**

2023-09-20 13:01 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/57/console)**

2023-09-20 13:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/57/)<br/>**

2023-09-20 15:11 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/58/console)**

2023-09-20 15:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/58/)<br/>**

2023-09-27 11:01 UTC, gobalakrishnans requested changes

2023-09-27 11:01 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/how-to/import-file-using-uploader.md
> +If you select the file using file uploader then you will get the uploaded file data in the [`success`](../api/uploader#success) event of file uploader. In this event, you should pass the received fil
Don't highlight the API names and methods

2023-09-27 11:01 UTC, gobalakrishnans commented on ej2-javascript/code-snippet/spreadsheet/import-using-uploader/index.js
> +//Render initialized Spreadsheet component
Remove the unwanted comment lines

2023-09-27 11:01 UTC, gobalakrishnans commented on ej2-javascript/code-snippet/spreadsheet/import-using-uploader/index.ts
> +//Initialize the SpreadSheet control
Remove the unwanted comment lines

2023-09-27 11:01 UTC, gobalakrishnans commented on ej2-javascript/code-snippet/spreadsheet/import-using-uploader/index.ts
> +// Initialize the uploader component
Remove the unwanted comment lines

2023-09-27 13:44 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/import-using-uploader/system.config.js
> +        "@syncfusion/ej2-navigations": "syncfusion:ej2-navigations/dist/ej2-navigations.umd.min.js",
Added the package

2023-09-27 13:50 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/import-using-uploader/index.ts
> +// Initialize the uploader component
removed

2023-09-27 13:50 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/import-using-uploader/index.ts
> +//Initialize the SpreadSheet control
removed

2023-09-27 13:50 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/import-using-uploader/index.js
> +//Render initialized Spreadsheet component
removed

2023-09-27 14:06 UTC, sangeetha-priya-M commented on ej2-javascript/spreadsheet/ej2-typescript-spreadsheet-toc.html
> +<li><a href="/ej2-typescript/spreadsheet/how-to/import-file-using-uploader">Import an excel file using uploader component</a></li>
modified

2023-09-27 14:06 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/import-using-uploader/system.config.js
> +        "@syncfusion/ej2-navigations": "syncfusion:ej2-navigations/dist/ej2-navigations.umd.min.js",
modified

2023-09-27 14:06 UTC, sangeetha-priya-M commented on ej2-javascript/spreadsheet/how-to/import-file-using-uploader.md
> +title: Import an excel file using uploader component in ##Platform_Name## Spreadsheet control | Syncfusion
modified

2023-09-27 14:06 UTC, sangeetha-priya-M commented on ej2-javascript/spreadsheet/how-to/import-file-using-uploader.md
> +## Import an excel file using uploader component in ##Platform_Name## Spreadsheet control
modified

2023-09-27 14:06 UTC, sangeetha-priya-M commented on ej2-javascript/spreadsheet/how-to/import-file-using-uploader.md
> +If you select the file using file uploader then you will get the uploaded file data in the [`success`](../api/uploader#success) event of file uploader. In this event, you should pass the received fil
modified

2023-09-27 14:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/61/console)**

2023-09-27 14:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/61/)<br/>**

2023-09-28 06:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/63/)<br/>**

2023-09-28 06:59 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/64/)<br/>**

2023-09-28 07:26 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/65/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-09-28 07:27 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/66/console)**

2023-09-28 07:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/66/console)**

2023-09-28 07:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/66/)<br/>**

2023-09-28 14:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/69/console)**

2023-09-28 15:04 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/70/console)**

2023-09-28 15:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/70/console)**

2023-09-28 15:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [822850-dev-ss](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/70/)<br/>**

2023-10-03 03:41 UTC, gobalakrishnans approved these changes

2023-10-03 03:42 UTC, merged