Added ROUNDDOWN formula snippets into the custom defined function.
syncfusion-content/ej2-spreadsheet-docs pull request #40
Opened 2023-09-08 18:35 UTC by Vasanth-3519

**Description:**
Modified the existing user defined function content and added round down formula snippets into the source.

2023-09-08 18:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/53/console)**

2023-09-08 18:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/53/)<br/>**

2023-09-13 13:12 UTC, gobalakrishnans requested changes

2023-09-27 22:54 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/formula-cs1/index.js
> +      //  store zero's upto provided negative digit.
modified with proper casing

2023-09-27 23:07 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/formula-cs1/index.ts
> +function RoundDownFunction(value: string, digit: any ) {
as the digit may contain positive negative as well as decimal considered as any rtype. Now, modified it.

2023-09-27 23:17 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/formula-cs1/index.ts
> +        spreadsheet.addCustomFunction(RoundDownFunction, 'ROUNDDOWN');
changed

2023-09-27 23:18 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/formulas.md
> +Almost all spreadsheet computations can be implemented using the available [`list of supported formulas`](https://ej2.syncfusion.com/documentation/spreadsheet/formulas#supported-formulas).
updated

2023-09-27 23:19 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/formulas.md
> +If you need formulas that are not supported by spreadsheet, you can add your own custom function using the [`addCustomFunction`](../api/spreadsheet/#addcustomfunction) method. You can also use [`comp
changed

2023-09-27 23:20 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/formulas.md
> +This custom function method can be used only for formulas whose results are updated to a single cell value. The formulas that return the result as an array will be tedious to achieve in this case.
updated

2023-09-27 23:23 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/formula-cs1/index.ts
> +    if (valueMode === 1) {
shared a modified sample for review. If its fine will update it and commit.

2023-09-27 23:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/62/console)**

2023-09-27 23:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/62/console)**

2023-09-27 23:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/62/)<br/>**

2023-09-28 07:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/67/console)**

2023-09-28 07:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/67/)<br/>**

2023-09-28 08:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/68/)<br/>**

2023-09-28 15:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/71/)<br/>**

2023-10-03 14:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/72/console)**

2023-10-03 14:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/72/)<br/>**

2023-10-03 14:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [custom-formula](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/73/)<br/>**

2023-10-17 12:08 UTC, gobalakrishnans approved these changes

2023-10-17 12:08 UTC, merged