860306: Added get filtered row details in how to section of spreadsheet.
syncfusion-content/ej2-spreadsheet-docs pull request #78
Opened 2023-12-19 05:20 UTC by Vasanth-3519

**Description:**
Added get filtered row details in how to section of spreadsheet documentation.

2023-12-19 05:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/149/)<br/>**

2023-12-19 10:24 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.js
> +        // Applies cell and number formatting to specified range of the active sheet
Remove the number formatting comments, just mention only cell formats

2023-12-19 10:29 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.js
> +    if (spreadsheet) {
Remove the unwanted conditions

2023-12-19 10:29 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.ts
> +        // Applies cell and number formatting to specified range of the active sheet
Modify the comments

2023-12-20 04:13 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.js
> +        // Applies cell and number formatting to specified range of the active sheet
Addressed and modified

2023-12-20 04:14 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.js
> +    if (spreadsheet) {
Addressed and modified

2023-12-20 04:15 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.ts
> +        // Applies cell and number formatting to specified range of the active sheet
Addressed and modified

2023-12-20 04:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/153/)<br/>**

2023-12-20 05:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/154/console)**

2023-12-20 05:41 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/154/)<br/>**

2023-12-22 08:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/157/console)**

2023-12-22 08:58 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/157/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-12-22 08:59 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/158/console)**

2023-12-22 09:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/158/console)**

2023-12-22 09:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/158/)<br/>**

2023-12-22 09:39 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.js
> +    allowFiltering: true,
remove the allowFiltering property in code block

2023-12-22 09:39 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.js
> +// Render initialized Spreadsheet.
Remove the unwanted comment lines

2023-12-22 09:40 UTC, sangeetha-priya-M commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.ts
> +    allowFiltering: true,
remove filtering api

2023-12-22 09:44 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.js
> +    allowFiltering: true,
removed.

2023-12-22 09:44 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.js
> +// Render initialized Spreadsheet.
removed

2023-12-22 09:44 UTC, Vasanth-3519 commented on ej2-javascript/code-snippet/spreadsheet/filter-cs2/index.ts
> +    allowFiltering: true,
removed

2023-12-22 09:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/159/console)**

2023-12-22 09:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/159/)<br/>**

2023-12-22 11:17 UTC, gobalakrishnans requested changes

2023-12-22 11:17 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/ej2-javascript-spreadsheet-toc.html
> +<li><a href="/ej2-javascript/spreadsheet/how-to/get-filtered-row-details">Get filtered row details</a></li>
file name : get-filtered-rows

Content: Get filtered rows

2023-12-22 11:17 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/how-to/get-filtered-row-details.md
> +title: Get the filtered row details in the ##Platform_Name## Spreadsheet control | Syncfusion
Get the filtered rows in ##Platform_Name## Spreadsheet control | Syncfusion

2023-12-22 11:17 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/how-to/get-filtered-row-details.md
> +description: Learn here all about how to get the filtered row details in Syncfusion ##Platform_Name## Spreadsheet control of Syncfusion Essential JS 2 and more.
Learn here all about how to get the filtered rows in Syncfusion ##Platform_Name## Spreadsheet control of Syncfusion Essential JS 2 and more.

2023-12-22 11:17 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/how-to/get-filtered-row-details.md
> +## Get the filtered row details in ##Platform_Name## Spreadsheet control
## Get the filtered rows in ##Platform_Name## Spreadsheet control

2023-12-22 11:17 UTC, gobalakrishnans commented on ej2-javascript/spreadsheet/how-to/get-filtered-row-details.md
> +Filtering helps you to view specific rows in the spreadsheet by hiding the other rows. You can use the [allowFiltering](https://ej2.syncfusion.com/documentation/api/spreadsheet/#allowfiltering) prope
Filtering allows you to view specific rows in a spreadsheet by hiding the other rows. You can enable or disable filtering functionality using the allowFiltering property. You can also use the applyFilter method to filter the data. The filtered rows can be obtained by using the isFiltered property on each row.

2023-12-22 11:42 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/ej2-javascript-spreadsheet-toc.html
> +<li><a href="/ej2-javascript/spreadsheet/how-to/get-filtered-row-details">Get filtered row details</a></li>
Modified as instructed

2023-12-22 11:44 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/how-to/get-filtered-row-details.md
> +title: Get the filtered row details in the ##Platform_Name## Spreadsheet control | Syncfusion
Changed.

2023-12-22 11:45 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/how-to/get-filtered-row-details.md
> +description: Learn here all about how to get the filtered row details in Syncfusion ##Platform_Name## Spreadsheet control of Syncfusion Essential JS 2 and more.
Changed.

2023-12-22 11:46 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/how-to/get-filtered-row-details.md
> +## Get the filtered row details in ##Platform_Name## Spreadsheet control
Changed.

2023-12-22 11:47 UTC, Vasanth-3519 commented on ej2-javascript/spreadsheet/how-to/get-filtered-row-details.md
> +Filtering helps you to view specific rows in the spreadsheet by hiding the other rows. You can use the [allowFiltering](https://ej2.syncfusion.com/documentation/api/spreadsheet/#allowfiltering) prope
Modified the content as shared.

2023-12-22 11:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/161/console)**

2023-12-22 11:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/161/)<br/>**

2023-12-22 12:34 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/162/console)**

2023-12-22 12:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/162/console)**

2023-12-22 12:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/162/)<br/>**

2023-12-22 13:37 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/163/console)**

2023-12-22 13:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/163/console)**

2023-12-22 13:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [get-filtered-row-data](https://jenkins.syncfusion.com/job/Content/job/ej2-spreadsheet-docs/163/)<br/>**

2023-12-26 02:28 UTC, gobalakrishnans approved these changes

2023-12-26 02:28 UTC, merged